name: football_trivia
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: ^4.1.4

  # Network
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  # User interface
  fluttertoast: ^8.0.7
  webview_flutter: ^2.0.2
  flutter_local_notifications: ^6.0.0
  percent_indicator: ^3.3.0-nullsafety.1
  flutter_staggered_grid_view: ^0.4.0

  # Data
  get_storage: ^2.0.1
  intl: ^0.17.0
  json_annotation: ^4.0.0
  url_launcher: ^6.0.2

  # Firebase
  firebase_core: "^1.2.1"
  firebase_crashlytics: "^2.0.5"
  firebase_messaging: "^10.0.1"

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/product_sans_regular.ttf
          weight: 400
        - asset: fonts/product_sans_bold.ttf
          weight: 700
